### ISSUE TITLE
[gi] Strings in Preferences dialog gets cut off on locales with wider text

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#117]
Our Preferences dialog is kind of irritating to use on locales with much wider text than English (e.g. ru_RU). This is more apparent when a plugin with a long title is enabled, for example Pause on Screensaver, because it causes the treeview on the left to expand and take up half the window.

We can simply make the window wider by default, but at some point we'll be tempted to add more stuff horizontally and re-introduce the problem (see the two checkboxes in the Plugins section).

Is there a way to make the window take as much space as necessary to show all the text? And perhaps the left treeview shouldn't expand?

@genodeftest: Do you want to take this bug?

**Comment by genodeftest** [comment]
This is an issue I might have introduced when redesigning the preferences dialogs. I'll try to fix that.

For user experience I think the best solution would be to dynamically resize the window as needed (if that is possible). If it isn't possible the checkbox text should line-break, which I don't like (afaik I would have to edit every single glade file for preferences panes).

I set the treeview to expand because there this removed another issue where you either have a horizontal scrollbar (which is inconvenient) or you have to resize the panel between the treeview and preferences pages (inconvenient too). I would like to keep it that way, if no one disagrees.

For the preferences/plugins: I think this page could use a redesign anyway, and I guess you were thinking the same when writing https://github.com/exaile/exaile/pull/106#issuecomment-112257254

**Comment by genodeftest** [comment]
Ok, so there is some possiblities howto design this dialog:

## A: all sizes static
This is like it was before I did the first commit to the preferences dialog ui and how it looks like on master. We needed scrollpanes in both TreeView and preferences pane.
Pros: Simple to implement
Cons: static, bad user experience when text is too wide ⇒ user needs to scroll horizontally

## B: TreeView dynamic, preferences pane static
This is the current state in the gi branch. No scrollbars for both TreeView and preferences pane. Text in preferences pane can get cropped.
Pros: No horizontal scrolling at all
Cons: preferences pane is still static, same as above. User needs to resize window if content is too wide. This is bad.

## C: TreeView dynamic, preferences pane static but within a GtkScrolledWindow
This is currently broken in glade.
Pros: no horizontal scrolling in TreeView
Cons: still horizontal scrolling in preferences pane

## D: Both parts of the GtkPaned resize dynamically
Pros: No horizontal scrolling, no cropped content in windows
Cons: Bad for small monitors because preferences window is unpredictably wide. In rare cases the preferences window can become bigger than all available screen space together.

## E: complete rebuild of preferences view to get rid of the GtkPaned
Looks more like gnome-control-center or kde-system-settings: You have one overview page listing all available items and when you click on one of them you will get to the preferences.
Pros: Best solution for small monitors. Can use a GtkScrolledWindow here without problems
Cons: Complete rewrite necessary; preferences UI will be less clear to the user

## F: make all GtkCheckButtons break lines if they are too wide
Pros: Best available solution
Cons: Requires changing all glade files or a different plugin preferences API.

## Conclusion:
I am unsure whether to choose D or F. F would be perfect with a different preferences API where the xlgui package builds the CheckBoxes as opposed to the plugins (with glade .ui files). As a temporary (non-perfect) fix D would be enough in my opinion. What do you mean?

**Comment by genodeftest** [comment]
I added a simple fix (choice D) in #118. Please test with ru_RU locale, I can't do that because of the ascii/unicode bug.

**Comment by sjohannes** [comment]
Testing your patch, the largest I can get the prefs dialog with ru_RU locale is 845x664 ([screenshot](https://cloud.githubusercontent.com/assets/8440927/8323397/0f737c6e-1a87-11e5-91d4-f7a7223224d0.png)). Some observations:

* I don't really mind the 845 px width; the most terrible monitors these days are 1024x768, no? However, it could be a problem for someone trying to run Exaile on, say, a phone.
* We need at least a vertical scrollbar on the treeview. If we have more plugins with prefs it can grow taller indefinitely.
* Some particularly wide plugin prefs (like the screenshot shows with the Bookmarks plugin) cause the window to grow when the plugin is first selected on the treeview; not ideal but that's fine.

**Comment by genodeftest** [comment]
Ok, now the gi branch is starting up with `ru_RU` locale. It's still utterly broken (most cyrillic symbols are not displayed at all) but it starts and doesn't crash.
I'll think about the preferences dialog, this may take some time since the scrollbar will be problematic (how do I tell gtk to still try to resize the window until it is big enough to fill the screen?)

**Comment by virtuald** [comment]
So... one thought I had recently is that it might be nice to actually add the preferences stuff as a tab on the playlist tab, so it just shows up inline when selected. Or you could replace the entire window, or the right pane... this might make the default sizing issue moot.

I think I'd rather the treeview to be in a scrolled window, than the preferences.

F could work, but it'd be more work. Better to just fix the preferences dialogs that are too wide to be less wide.

**Comment by genodeftest** [comment]
So you would like to see the preferences as a tab (like Firefox/Chrome/Opera do) where the playlists belong?

**Comment by sjohannes** [comment]
I think I'd prefer it to stay as a window; it's more flexible in terms of positioning and lets us use the playlist while the Preferences window is open.

@genodeftest If you add a vertical-scroll-only scrolledwindow on the treeview (to accommodate more plugins), it should be good for now.

**Comment by genodeftest** [comment]
Done. Any more suggestions?

**Comment by sjohannes** [comment]
(Oops, was trying to see if I could set the bug assignment to you; turns out I couldn't.)

I've merged your latest PR, thanks. At the moment I can't think of any immediate issues with the Preferences dialog.
