### ISSUE TITLE
Exaile cannot remove a tag when collection is monitored

### ISSUE THREAD

**Issue by dangmai** [exaile/exaile#152]
I'm running Exaile 3.4.5 on Arch, and whenever I try to uncheck the last group from a song, it'd just be checked back immediately.

**Comment by virtuald** [comment]
Ha, neat! I've never noticed that before.

**Comment by virtuald** [comment]
I looked a little bit more at this tonight, sometimes it doesn't happen. It seems to only happen to monitored collections, and it doesn't just affect grouptagger. It seems to affect anything that tries to 'remove' a tag. 

An experiment I tried was to load the track properties dialog, and remove an arbitrary tag from a song (it was an ogg song, if that matters). You hit apply, and the tag disappears momentarily, only to reappear again a few moments later.

I turned on `--eventdebug` and it looks like it detects a bunch of changes and sends a lot of track_tags_changed events, followed by a tracks_added event. Not quite sure what to make of it. Still present in the GI branch.

**Comment by dangmai** [comment]
Interesting, I've definitely run into that before, tho I always attributed it to some songs having weird formats because it only affected some and not others. I'll try that again to see if I can get consistently reproducible behavior.

**Comment by virtuald** [comment]
FYI, I believe I've identified the underlying issue for this -- Exaile doesn't properly delete tags for some file formats (see #286), and when a collection is monitored then it will automatically read the tags back after a write occurs (because it can't tell that it was Exaile that made the write... probably should address that somewhere).

I'll push a fix soon.
