### ISSUE TITLE
Missing (flac/mp3) tag "URL"

### ISSUE THREAD

**Issue by sarnold** [exaile/exaile#182]
Both the track properties editor and the columns display are missing the URL tag.  The former shows a "website" tag in the Add Tag dialog, however it is not visible in the latter column display.  In other tag editors (eg, EasyTag) there is a URL tag which I normally fill with the archive.org page URL or other upstream site reference.

**Comment by virtuald** [comment]
What tag is missing? Can you post the output of `mutagen-inspect`?

**Comment by virtuald** [comment]
Nevermind, I think I misread.

**Comment by virtuald** [comment]
I did not misread. I added the `website` column, but I see that I cannot save the tag for mp3, while I can for flac. If you could post `mutagen-inspect` output for both files, that would be useful for resolving this.

**Comment by sarnold** [comment]
I don't think I've tried the mutagen tool for tag info (mostly the id3/mp3 console tools) so this looks a little strange:

```
$ mutagen-inspect flac/steve_kimock_band/magic_bag/skb2001-11-06d1t01.flac 
-- flac/steve_kimock_band/magic_bag/skb2001-11-06d1t01.flac 
- FLAC, 1123.08 seconds, 44100 Hz (audio/x-flac)
TITLE=You're The One
ARTIST=Steve Kimock Band
ALBUM=Magic Bag
DISCNUMBER=1
DATE=2001
TRACKNUMBER=01
TRACKTOTAL=11
GENRE=Fusion
DESCRIPTION=The Magic Bag, Ferndale, MI, 11-6-2001
CONTACT=https://archive.org/details/skb2001-11-06
ENCODED-BY=flac 

$ mutagen-inspect mp3/steve_kimock_band/magic_bag/skb2001-11-06d1t01.mp3 
-- mp3/steve_kimock_band/magic_bag/skb2001-11-06d1t01.mp3 
- MPEG 1 layer 3, 192000 bps (CBR?), 44100 Hz, 2 chn, 1123.11 seconds (audio/mp3)
TALB=Magic Bag
TCON=Fusion
TDRC=2001
TIT2=You're The One
TPE1=Steve Kimock Band
TPOS=01
TRCK=01/11
WXXX=https://archive.org/details/skb2001-11-06 
```

**Comment by sarnold** [comment]
I normally use mp3fs to make my mp3s from flac source, unless it's an mp3-only download like 30 Days of Dead.  They have an open issue for ID3v2.3 support:

https://github.com/khenriks/mp3fs/issues/42

**Comment by virtuald** [comment]
Ok, so Exaile maps 'website' to WOAR (there's apparently multiple of these tags), whereas WXXX is the "user specified custom URL". However, due to a quirk in the way mutagen deals with URL tags, it looks like exaile doesn't actually write *or* read it correctly.

On the flac side, apparently exaile writes 'website' as 'website', and ignores 'contact'. 

Looking at this [translation table](http://wiki.hydrogenaud.io/index.php?title=Tag_Mapping) which seems to be compiled from several sources, contact doesn't seem to have a commonly accepted mapping (but neither does WXXX -- though winamp apparently uses it as URL).

Mutagen's easyid3 wrapper reads/writes 'website' as 'WOAR', and doesn't deal with WXXX. I'm strongly thinking about switching to it, it supports just about every tag that we do and is less work.

**Comment by virtuald** [comment]
This seems to be addressed.
