### ISSUE TITLE
'Date added' is set to 'Never' for new tracks when copying new tracks in 'Monitored' collection folder

### ISSUE THREAD

**Issue by strahlc** [exaile/exaile#226]
I have a lot of tracks where the "Date added" column is set to "Never".
Where does this come from and how can I avoid that.
(I usually add Tracks by moving them in the montored folders and rescan the collection.)

**Comment by genodeftest** [comment]
For a reason why this happens, have a look at xl/formatter.py from line 685 on (or search for `DateTagFormatter`). This class `DateTagFormatter` was intended to be used for the "Last played" date (column) but has also been applied to the "Date added" date (column). In your case ("Date added" shows "Never"), the timestamp for the file is `None`. This happens when a file is not yet added to your collection.

Steps to reproduce the behavior you described:
1. add a file which is not in exaile's collection to a playlist
What happens:
Column "Date added" shows "Never"

Expected behavior (1):
1. add a file which is not in exaile's collection to a playlist
2. add folder containing this file to collection
What happens:
Column "Date added" changes to "Today"

Expected behavior (2):
1. add a folder to exaile's collection
2. add any file from exaile's collection to a playlist
What happens:
Column "Date added" shows "Today" or any previous date.

What could be done is improving column header text, e.g. from "Date added" to "Added to library". I'll file a pull request for that.

So there is nothing wrong with how the date is shown. Can you please make sure that these files really are in your collection? Use the collection panel and search for these files. If this file is not in your collection, this is not a bug. Maybe something went wrong adding these files to exaile's collection?

**Comment by strahlc** [comment]
Only about 25% of the file **in my collection** has the 'Date added' set to a date. All other files **in my collection** are set to 'Never'.
For example: I have an album in my collection where some tracks has the date added set correct while other tracks of the same album are set to never.

Expected behavior:
1. rescan collection
2. all files found by exaile in 'Monitored' folders should get a time stamp with the current time for date added, if they do not already have one.

**Comment by genodeftest** [comment]
Is there anything about these files in your exaile log files? Probably something went wrong monitoring/rescanning your collection. I still cannot reproduce it. Is anything special about these files like are they on a removable disk that might have been unavailable at least once when exaile started or was running?

Have you tried deleting the collection from exaile and adding it again?

**Comment by strahlc** [comment]
When I copy the album to a folder outside my collection and add add this folder in 'Collection Manager', the album appears twice and the newer one has all tracks with 'Date added' set to 'Today'.

**Comment by genodeftest** [comment]
Especially when you were using exaile for a big collection and/or over multiple development versions it is quite likely to break your database at some point (at least that is what happens to me sometimes).

**Comment by strahlc** [comment]
I've found a way to reproduce it:

1. add a folder in the 'Collection Manager'
2. **mark this folder as 'Monitored'**
3. copy a track in the monitored (sub)folder

What happens:
The file shows up immediately in the collection, but 'Date added' is set to never.
Even 'Rescan Collection' doesn't change 'Date added' for this track.

Expected behavior:
1. The file shows up immediately in the collection, and 'Date added' is set to the current date.

Crosscheck:
If a remove the 'Monitored' flag from the folder, copy a track inside it and then manually 'Rescan Collection' everything works fine ('Date added': 'Today').

**Comment by genodeftest** [comment]
I tried that too some hours ago but instead exaile crashed with a SEGV in python's interpreter or Gtk+ code.

Thanks for the reproducer! Hopefully it will help.

**Comment by sbrubes** [comment]
I'm not sure if it's a correct context to put a code to change a tag, but you could set tag at add_tracks on trackdb.py. https://github.com/exaile/exaile/blob/master/xl/trax/trackdb.py#L342

Inside 'for' add:
> tr.set_tag_raw('__date_added', time.time())

** _time must be imported_

Then you could remove it from https://github.com/exaile/exaile/blob/master/xl/collection.py#L727.

**Comment by genodeftest** [comment]
Thanks @sbrubes !
