### ISSUE TITLE
repeat+shuffle: Last track in playlist is not played again any more

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#247]
Steps to reproduce:
1. create a playlist with at least 2 items, 3 is ideal to show this bug
2. set shuffle mode to "shuffle tracks"
3. set repeat mode to "repeat all"
4. play
5. wait some time or press "next" button

What happens:
Last track in playlist is only played once, no matter how often you press "next".

What should happen:
Ideally (when pressing "next" very often) every track should be played (roughly) the same number of times.

Affects: current git master since at least 5 months

**Comment by genodeftest** [comment]
Why does this happen?
In xl/playlist.py, `PlayList.__next_random_track()`, `self.get_shuffle_history()` returns the last element in playlist even if it was not played before and even though the shuffle history was deleted before.

**Comment by sbrubes** [comment]
It happens because PlayList.__get_next() calls himself with current_position to -1 when don't have a next. https://github.com/exaile/exaile/blob/master/xl/playlist.py#L1150

**The solution** is to fix the condition to ignore current_position == -1, changing 
   `if self.current is not None:`
to
   `if current_position != -1:`
https://github.com/exaile/exaile/blob/master/xl/playlist.py#L1128

A point must be made at this issue, the way it's implemented today, it could repeat the "last song" choosing it as a 'first' on the next random set. For shuffling it's probably something that you don't want.

**Comment by genodeftest** [comment]
Thanks @sbrubes !

> A point must be made at this issue, the way it's implemented today, it could repeat the "last song" choosing it as a 'first' on the next random set. For shuffling it's probably something that you don't want.

I don't understand. Can you please explain in detail?

**Comment by sbrubes** [comment]
@genodeftest Could be not an issue:

Songs play as [3, 1, 2], it reaches the end of the list (current_position==-1), decides to play as [2, 3, 1] and plays in a sequence _music 2_: **[3, 1, 2] -> [2, 3, 1]** ...

If it could be a problem a workaround it's enough.

Probably it's a better idea implementing the history being a list, rather than flagged.

Still saying about shuffle, I believe that this history should be clean when you press Stop.
Maybe @virtuald could say it.

**Comment by genodeftest** [comment]
Sorry, those commits are unrelated but belong to #287 instead.

**Comment by sbrubes** [comment]
What about cleaning the history on 'stop'?

**Comment by genodeftest** [comment]
@sbrubes wrote:
> What about cleaning the history on 'stop'?

I'd take that as a separate issue.
