### ISSUE TITLE
Is there any roadmap or date for next release?

### ISSUE THREAD

**Issue by gnacho** [exaile/exaile#258]
I'm not a developer and sorry I can't really help with code but I do think this is the best audio player for Gnome/GTK and it's a shame not seeing new releases. I can help with translations, bug reporting, UI and other stuff tho.

**Comment by virtuald** [comment]
Well, if it works great, no need for new releases ;-)

It's code that is lacking at the moment -- there are several critical bugs that are remaining from our migration to GStreamer 1.x. During the winter I volunteer with FIRST Robotics, so it pretty much kills all of my free time. Season usually ends in March, but my team did really well, so won't be back to Exaile until mid-May I suspect.

**Comment by gnacho** [comment]
It is great but there are basic stuff like integration with Gnome Notifications, multimedia keys and some other small details that make it "look" a little bit older than the rest of options.
Apart from that everything is just great. Good work!!

PS: is there only you developing it? :open_mouth:

**Comment by virtuald** [comment]
Me and @sjohannes, and @genodeftest pitches in

**Comment by gnacho** [comment]
Is never a bad moment to "attrack" new developers and increase the community! ;-)

**Comment by genodeftest** [comment]
Last time I checked, Gnome Notifications were working (from both 3.4.x and master). Multimedia keys should work too. Both are provided by plugins (see preferences dialog). Quite recently, MPRIS2 support has landed in master, so gnome-shell 3.20 multimedia features are supported. Feel free to run/test the version from git master. As always: have backups!

I've been running it for months (~1 year) now and the only major issue I ran into was the encoding problem with python, so I had to delete and regenerate the library index.

If you're insterested, feel free to jump in. [This wiki page](https://github.com/exaile/exaile/wiki/PyGI-migration-tasklist-%28GTK3-GStreamer-1.x%29) lists the main stuff we want to have/fix before the next major release, most stuff is done here. [Some plugins](https://github.com/exaile/exaile/wiki/Exaile-4.x-Plugin-development-status-list) are not ported yet or untested. Other than that we have [some issues], about 20…40% of them affect the planned 4.0 version, and about 10 of them are release-critical.

**Comment by slmeyer** [comment]
Really my favourite music player due to the Moodbar plugin and the generally sensible design.

I have also used Aqualung, which has a choice of several sampling algorithms / resolutions in case playback device and audio file sampling rate is unequal, so you can choose what your processor is up to. I guess Exaile leaves all that to the Gstreamer backend, does that leave any room for choices like that?
Another small thing is the links to 'gi branch' are defunct in these github info pages:
"Check out our progress on the 'gi' branch on github."

Thanks a lot for a great music player!

**Comment by sjohannes** [comment]
> I have also used Aqualung, which has a choice of several sampling algorithms / resolutions in case playback device and audio file sampling rate is unequal, so you can choose what your processor is up to. I guess Exaile leaves all that to the Gstreamer backend, does that leave any room for choices like that?

It's technically possible, though I'm not sure how easy it is to do with how we use GStreamer.

(For anyone interested in working on this, [audioresample](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gst-plugins-base-plugins/html/gst-plugins-base-plugins-audioresample.html) allows changing the resampling quality, but we use playbin and I don't know if it's possible to change the defaults there.)

> Another small thing is the links to 'gi branch' are defunct in these github info pages:

Thanks, I've replaced that text. The gi branch has been merged to master. If you want to test it, the [DEPS](https://github.com/exaile/exaile/blob/master/DEPS) file lists the dependencies you need to install. Backup `~/.config/exaile` and `~/.local/share/exaile` just in case.

The Moodbar plugin was rewritten (because the drawing API it used has been removed in GTK+ 3) so it would be interesting to get testing from someone that uses it regularly.

**Comment by gnacho** [comment]
Is not working for me. Is it maybe some dependency missing? I'm using Arch (Apricity) and installed from AUR repo.

**Comment by virtuald** [comment]
Closing, as this isn't an issue.
