### ISSUE TITLE
Ubuntu 16.04 / KDE : Tray Icon is extremely tiny

### ISSUE THREAD

**Issue by Hackswell** [exaile/exaile#259]
The tray icon in KDE is super super tiny!  Attached is a screenshot of my tray.
Running from GitHub master (4.0x) checked out on 2016-04-26.

![exailetinyicon](https://cloud.githubusercontent.com/assets/2632004/14823202/9e77e404-0b9f-11e6-99eb-afd8c2977657.png)

Thanks for all of your hard work, folks!

**Comment by virtuald** [comment]
Ok, this is totally messed up on my box too -- only shows a quarter icon. I created a bit of code that creates a `StatusIcon` object, and the status icon works fine. No problems.

[Here's the code if someone cares](https://gist.github.com/virtuald/0a9143a0f4ec54327bbf75001f1d6dcf).

I also tried creating one manually in the IPython console in Exaile:

```python
from gi.repository import Gtk
i = Gtk.StatusIcon()
i.set_icon_from_name('exaile')
```

This ALSO works fine. Ok. Stupid. I mess around some more. I toggle the setting to turn it on and off, and about 30% of the time I get a full icon, the other 70% I get the quarter icon.

This has to be some esoteric GTK bug, probably because of something stupid the code is doing somewhere else. If I were to guess, there's a thread somewhere that's corrupting the IconTheme. But who knows.

Gtk.StatusIcon is deprecated as of 3.14 anyways, so I'm inclined to not spend any more time on this.

**Comment by genodeftest** [comment]
@Hackswell : I cannot reproduce the bug you described. I am using [4.0.0 beta 2](https://github.com/exaile/exaile/releases/latest). If you still can (with that version or a later one), please add a comment here and reopen this issue. If not, I assume the issue is gone.
