### ISSUE TITLE
'New Playlist' button on the left instead of right

### ISSUE THREAD

**Issue by cipricus** [exaile/exaile#267]
Version 3.4.5

Current behavior:

New Playlist button is to the right of the playlists tab ( upper right area of the player's window): using the player's file explorer (_Files_ tab which is at the extreme left) drag&dropping a directory on the button creates a new playlist for that directory. But drag&drop from the file explorer (left margin of the player's window) to the 'New Playlist' button (upper-right part of the player's window) is cumbersome, especially on a laptop touchpad.

Expected behavior:

'New Playlist' button left of the playlist tabs, close to the 'Files' tab (file explorer area). Drag&dropping files and folders on the 'New Playlist' button becomes much easier.

**Comment by tfree87** [comment]
One simple fix for this is to just change the pack type from `END` to `START` for all the action buttons in notebooks. This can be seen in this commit I made a496930f4dd3d5d9c9cadf163384f5d0f54d6547. Making this change, however, will change this property for any notebook which uses the `NotebookAction` class. I will try to see I can make this optional so that it can be changed on a per-notebook basis. That will allow each notebook which uses action buttons to have the buttons placed either on the left or the right indivdually.

**Comment by tfree87** [comment]
Here (1a244aa8ea6c1caa775c991fdb1a6a1988d0b93e) is a solution where action buttons for the playlist notebook are now on the left side without changing the default packing of notebook actions for any other actions that may be added to other notebooks.

**Comment by virtuald** [comment]
Fixed for Exaile 4.0.
