### ISSUE TITLE
Exaile 4 in  Debian Stretch

### ISSUE THREAD

**Issue by javiercantero** [exaile/exaile#308]
I don't know if the plan was for Exaile 4 to be in the next Debian stable, but the deadline for letting new packages in Stretch (or restoring those that have been removed) is January 5, 2017 (soft freeze). And I  assume that Exaile 4 is not going to be ready in a couple of weeks... :-(

**Comment by virtuald** [comment]
There are ~17 issues in [Exaile 4.0 Milestone](https://github.com/exaile/exaile/milestone/2) ... I suspect that we could knock out the ones that matter by the end of the year if we really tried (I've moved insignificant bugs or enhancements to 4.0.1 milestone). I personally have had other priorities and haven't found the time to do it. I might be able to find the time.

The problem is that some of the remaining issues are rather big and annoying (drag and drop, async io breakage, various freezes). Sigh.

**Comment by javiercantero** [comment]
Has anyone talked to the [former Debian Maintainer](https://tracker.debian.org/pkg/exaile)? One possibility is to release a 4-RC1 version in order to reintroduce the package in the archive and meet the January 5 deadline. This way, there would be another month of debbugging/patching until the full freeze (on [February 5](https://wiki.debian.org/DebianStretch)).

**Comment by javiercantero** [comment]
Stretch is [already in soft freeze](https://lists.debian.org/debian-devel-announce/2017/01/msg00002.html), so I'm going to close this issue as unresolved. Exaile 4.0 won't be in the next stable Debian release. :-(
