### ISSUE TITLE
Gstreamer was not found

### ISSUE THREAD

**Issue by mrkaban** [exaile/exaile#370]
Hello, the installer can not download gstreamer, so I downloaded it and installed it manually. However, when you run the program, you receive an error "Gstreamer was not found. It can be downloaded from www.gstreamer.com".

operating system Windows 7 x64.

**Comment by virtuald** [comment]
We should probably take the current releases down. We will have a beta release soon, which will address these issues... for now, see our [developer documentation](http://exaile.readthedocs.io/en/latest/dev/getting_started.html#setting-up-a-development-environment) for how to get started with Exaile + msys2 on Windows. 

Otherwise, subscribe to our mailing list and there will be an announcement when the beta is released. Any day now!

**Comment by virtuald** [comment]
@mrkaban The beta release is now available.

**Comment by mrkaban** [comment]
Working! Tell me please, is there a file association planned? And are there any translations?

I would like to help translate into Russian, but I'm very concerned about the association of files.

**Comment by virtuald** [comment]
There are translations, see https://hosted.weblate.org/projects/exaile/master/ ... they should show up for you. If not, then that's a bug (file it separately).

I haven't really thought very much about file associations. That would also be a separate bug... it should be pretty straightforward to do in the installer.

**Comment by mrkaban** [comment]
I understand that you probably do not need it. I just want to help. Recently watched a video player, and there was an association of files with the help of this script. Suddenly help.

Visitors to my site are very critical association of files. Thank you.
[mpv-install.zip](https://github.com/exaile/exaile/files/1023052/mpv-install.zip)
