### ISSUE TITLE
4.0.0beta2: no progress bar -xubuntu16.04

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#412]
Hi.
Testing Exaile 4.0.0beta2 with xubuntu16.04.
Happy to ear .wma/.mp3 issue resolved, but I can't see the progress bar nor the track time.
Note: even not showed, the progress bar works-> I can go back or forward by clicking in this supposed area. 

### Environment
![exaile4-nobar](https://user-images.githubusercontent.com/4454843/27840086-9a84157c-60f6-11e7-80f8-9838421ba0ba.png)
* Exaile Version: 4.0.0beta2
GStreamer: 1.8.3
GTK+: 3.18.9
Locale: fr_FR UTF-8
Mutagen: 1.31
PyGObject: 3.20.0
Python: 2.7.12

**Comment by genodeftest** [comment]
Hi and thanks for testing and reporting back!

Can you upload a screenshot please? What is your Gtk+ theme?

**Comment by XzuRukneg** [comment]
Can't you see the screen-shot in my 1st message? 
The mouse cursor is where the progress bar is supposed to be. 
Gtk theme: clearlooks

**Comment by XzuRukneg** [comment]
Can't you see the screen-shot in my 1st message?
The mouse cursor is where the progress bar is supposed to be.
Gtk theme: clearlooks

**Comment by genodeftest** [comment]
> Can't you see the screen-shot in my 1st message?

Oh, sorry, my browser broke the page due to a content blocker…. After un-blocking it I can see the screenshot, thanks!

It seems like your theme on Exaile is _not_ Clearlooks. Clearlooks is a Gtk+ 2 theme, not a Gtk+ 3 theme, but Exaile 4.0.0 is running with the latter. There is a port of Clearlooks to Gtk+ 3, [clearlooks-phénix](https://github.com/jpfleury/clearlooks-phenix), but it looks very different from what you are using. In case you are using clearlooks-phénix, you should try to update it. 
Can you please try with the default Gtk+ 3 theme, Adwaita? This can e.g. be done by running `GTK_THEME=Adwaita ./exaile` instead of `./exaile` from the directory where you put the Exaile beta. Anyway, your theme _almost_ looks like Adwaita already.

Do you see any warnings in Exaile's output (from command line) or recent log files (have a look at `~/.cache/exaile/logs/`)?

**Comment by XzuRukneg** [comment]
> GTK_THEME=Adwaita ./exail

Nothing change.

> Do you see any warnings in Exaile's output

Yes!
[https://pastebin.com/XLdBvMxD]

Another thing (sorry for off topic): where are stored the play-list? I would like to get back some from another system (another distro using same collection). 
Thanks!

**Comment by sjohannes** [comment]
> ```pytb
> Traceback (most recent call last):
>   File ".../xlgui/widgets/playback.py", line 434, in do_draw
>     Gtk.ProgressBar.do_draw(self, context)
> KeyError: 'could not find foreign type Context'
> ```

I think this means it's missing Pycairo. Could you check if the python-cairo package is installed?

> Another thing (sorry for off topic): where are stored the play-list? I would like to get back some from another system (another distro using same collection).

They're in `~/.local/share/exaile` under `saved_tabs`, `playlists`, and `smart_playlists`, depending on which ones you're interested in. They're all simple text files, you can open them with a text editor to check the contents.

**Comment by XzuRukneg** [comment]
I got this:
![ex-py](https://user-images.githubusercontent.com/4454843/28037154-c2c11634-65ba-11e7-9659-fe0f4cfaf169.png)

Thx for the playlist. It looks like I've got some issue in, so I may open another thread!

**Comment by genodeftest** [comment]
@XzuRukneg : If the issue is still present for you, can you please try installing the python-gi-cairo package? Does that solve your issue? If yes, where did you install Exaile from, from source or from a repository/PPA?

This is pretty weird since the xlgui/widgets/playback.py does not import any cairo module, neither the native cairo port, nor the GI or the CFFI version…

**Comment by XzuRukneg** [comment]
@genodeftest: one more time image blocked? :)

**Comment by sjohannes** [comment]
@XzuRukneg: There's a `python-cairo` and a `python-gi-cairo` package. Try installing the `-gi-` one. I think we don't need it, but give it a try.

**Comment by genodeftest** [comment]
> @genodeftest: one more time image blocked? :)

No, I can see the screenshot of your apt frontend (was it synaptic?)

> There's a python-cairo and a python-gi-cairo package. Try installing the -gi- one. I think we don't need it, but give it a try.

That's what I meant, exactly.

**Comment by XzuRukneg** [comment]
Python3-gi-cairo war already installed, as you can see on the synaptic package manager screen-shot. The red square are installed ones. 
Installed from source from official site.

**Comment by genodeftest** [comment]
> python-gi-cairo and not python3-gi-cairo, ah ok!

Does that solve the issue?

**Comment by XzuRukneg** [comment]
![exaile-progressbar](https://user-images.githubusercontent.com/4454843/28113992-21de09fc-66ff-11e7-9a6a-90156bf3a2ba.png)
That works! :) thx
Installed from source from official site.

**Comment by genodeftest** [comment]
Ok, thanks for your feedback!
I added a note to the DEPS file.
