### ISSUE TITLE
Segmentation fault when adding too many files from sftp mounted dir

### ISSUE THREAD

**Issue by jondoe1337** [exaile/exaile#424]
Exaile crashes when adding too big files to the playlist

### Steps to Reproduce (for bugs)
1. Mount a directory with mp3s using sftp (e.g. gigolo)
2. Browse to the directory within the files tab in exaile
3. Try to move them in the playlist (size of all mp3s was around 71MByte

### Expected Behavior
Should not crash

### Current Behavior
Segmentation fault

### Environment
source: git exaile
branch: master
commit: e2543b4588e30f415766b67e55ee9235fc444593

**Comment by genodeftest** [comment]
Hi @jondoe1337, thanks for this report. Can you please gives us a few more details:
Which system are you using?
If it is not Windows, can you please get us a backtrace? To get it, please follow these steps:

1. Install [gdb](https://en.wikipedia.org/wiki/GNU_Debugger) and debug symbols for Python 2, GLib 2 and Gtk+ 3. How to do that depends on your distribution. If you don't know how, please ask.
2. open a terminal
3. use the `cd` command to change to the directory where you put Exaile source code.
4. run `gdb /usr/bin/python2`
5. in gdb, run `run ./exaile.py --startgui`. You might append other arguments if you need them.
6. use Exaile as you did before and try to reproduce the problem. At some point, exaile might freeze. This is when gdb catched the segmentation fault.
7. in gdb, run `set logging on exaile-segfault.txt` followed by `t a a py-bt` and `t a a bt full`. You might need to type the return key a few times after the last two commands.
8. now type `quit`
9. please attach the file `exaile-segfault.txt` here after you checked that it does not contain any private data. If you prefer to send the data encrypted, please feel free to send them to me (see my account for email address) and encrypt it agains PGP key ID 0x545B42FB8713DA3B.

**Comment by jondoe1337** [comment]
Hi @genodeftest I will try it, but it would be helpful to know which packages include the python2, glib2 and gtk+3 debug symbols.

I'm using xubuntu 16.04 with 4.4.0-88-generic / x86_64

**Comment by genodeftest** [comment]
> I'm using xubuntu 16.04

That's the info I needed to answer this question, because installing debug symbols differs between Linux distros.

On Debian/Ubuntu and flavors, you can get packages by installing their `-dbg`-version. For firefox, the debug symbols would be contained in `firefox-dbg`. In this case, the package names probably are: `libgtk-3-dbg`, `python2.7-dbg` and `libglib2.0-dbg`. You might want to use Synaptic (a GUI for package management) or run `apt-get install <packagename>` as root or sudo in a terminal to install these packages.

Also, the Ubuntu wiki might help:
* https://wiki.ubuntu.com/Backtrace
* https://wiki.ubuntu.com/DebuggingProgramCrash#Installing_debug_symbols_manually

**Comment by jondoe1337** [comment]
At task 5. the start of exaile fails with:

```
(gdb) run ./exaile.py --startgui
Starting program: /usr/bin/python2 ./exaile.py --startgui
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
INFO    : Loading Exaile 4.0.0beta2+e2543b4...
INFO    : Using Python 2.7.12
INFO    : Using PyGObject 3.20.0
INFO    : Loading settings...
INFO    : Using Locale en_US UTF-8
INFO    : Loading plugins...
/home/jondoe/sandbox/exaile/plugins/notifyosd/__init__.py:26: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
ERROR   : Unable to enable plugin notifyosd
Traceback (most recent call last):
  File "/home/jondoe/sandbox/exaile/xl/plugins.py", line 148, in enable_plugin
    plugin = self.load_plugin(pluginname)
  File "/home/jondoe/sandbox/exaile/xl/plugins.py", line 87, in load_plugin
    plugin = imp.load_source(pluginname, os.path.join(path, '__init__.py'))
  File "/home/jondoe/sandbox/exaile/plugins/notifyosd/__init__.py", line 28, in <module>
    from xl import (
  File "/home/jondoe/sandbox/exaile/xl/covers.py", line 43, in <module>
    from xl import (
  File "/home/jondoe/sandbox/exaile/xl/trax/__init__.py", line 34, in <module>
    from xl.trax.track import Track
  File "/home/jondoe/sandbox/exaile/xl/trax/track.py", line 38, in <module>
    from xl import (
  File "/home/jondoe/sandbox/exaile/xl/metadata/__init__.py", line 31, in <module>
    from xl.metadata._base import BaseFormat, CoverImage, NotWritable, NotReadable
  File "/home/jondoe/sandbox/exaile/xl/metadata/_base.py", line 34, in <module>
    import mutagen
ImportError: No module named mutagen
INFO    : Loading collection...
ERROR   : Unhandled exception
Traceback (most recent call last):
  File "/home/jondoe/sandbox/exaile/xl/main.py", line 346, in __init__
    self.__init()
  File "/home/jondoe/sandbox/exaile/xl/main.py", line 447, in __init
    from xl import collection
  File "/home/jondoe/sandbox/exaile/xl/collection.py", line 45, in <module>
    from xl import (
  File "/home/jondoe/sandbox/exaile/xl/trax/__init__.py", line 34, in <module>
    from xl.trax.track import Track
  File "/home/jondoe/sandbox/exaile/xl/trax/track.py", line 38, in <module>
    from xl import (
  File "/home/jondoe/sandbox/exaile/xl/metadata/__init__.py", line 31, in <module>
    from xl.metadata._base import BaseFormat, CoverImage, NotWritable, NotReadable
  File "/home/jondoe/sandbox/exaile/xl/metadata/_base.py", line 34, in <module>
    import mutagen
ImportError: No module named mutagen
[Inferior 1 (process 17186) exited normally]
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
```

I installed libgtk2.0-0-dbg libgtk-3-0-dbg python2.7-dbg but Iam there is no python mutagen dev/dbg package. Any idea?

**Comment by genodeftest** [comment]
> I installed libgtk2.0-0-dbg libgtk-3-0-dbg python2.7-dbg but Iam there is no python mutagen dev/dbg package. Any idea?

Yes, python-mutagen does not have/need a debug package, but you will need to install the (regular) python mutagen package to make exaile run.

**Comment by jondoe1337** [comment]
The remaining package that needed to be installed is: `python-mutagen`
[exaile-segfault.txt](https://github.com/exaile/exaile/files/1207513/exaile-segfault.txt)
There you go!

**Comment by genodeftest** [comment]
@jondoe1337 : Thank you!

I guess this issue is happening in thread 3 in the logfile above. What I think happens in `xlgui.widgets.common.DragTreeView`:
1. the drag operation causes `on_drag_begin()` to be called with a `Gdk.DragContext` as `context`.
2. `_on_drag_begin()` is called async, because of `@common.threaded`.
3. `_set_drag_cover()` is being called on the main thread through `GLib.idle_add()`
4. At this time, the `context` object might be invalid, e.g. because the drag operation has finished already.

This issue is triggered by threading (a race condition) and looks like a use-after-free bug.  The question is: Is Exaile code allowed to assume this `context` object still exists? I.e. is this a Gtk+ bug, or one in Exaile? IMHO the Gtk+ documentation is not clear about that. Exaile is not doing any threading stuff wrong, because it does not access that object anywhere but on the main thread.

@jondoe1337 (optional:) If you know how to use valgrind, you might want to confirm this use-after-free by running Exaile under valgrind such as `G_DEBUG=gc-friendly G_SLICE=always-malloc,debug-blocks valgrind --vgdb=full --vgdb-error=0 /usr/bin/python2 ./exaile.py --startgui`, attach gdb to it  (valgrind will tell you how to do this) and post valgrind's output. This will show us where the `context` object has been destroyed. I am not 100% sure this issue can be reproduced in valgrind though, because valgrind is so slow….

If someone wants to dig deeper, Mozilla's [rr](https://en.wikipedia.org/wiki/RR_(debugging)) is a more powerful tool which allows you to go back in time.

**Comment by virtuald** [comment]
The context probably should not be accessed from a different thread, but should be copied instead.

**Comment by virtuald** [comment]
I'm guessing we can't use the context.

**Comment by jondoe1337** [comment]
Well - I have never heard of valgrind. :)

**Comment by genodeftest** [comment]
> Well - I have never heard of valgrind. :)

No problem.

> I'm guessing we can't use the context.

Ok, looks like a good solution. We might disable the "show covers on drag" feature for now. I won't be able to really fix this for >1 week.

**Comment by jondoe1337** [comment]
That makes sense.

I guess some features that exaile gives, are not meant to be used for remote files. 

That's why the start of exaile takes very long for me...but that might me another story. New issue?

**Comment by sjohannes** [comment]
I think this is the same or related to #67.

**Comment by genodeftest** [comment]
@sjohannes , @virtuald :
Should we remove this feature (showing cover icons on drag) completely, or just comment it out?

**Comment by virtuald** [comment]
I'm fine with either solution.

**Comment by genodeftest** [comment]
@jondoe1337 or anyone else who has been able to reproduce this crasher: Can you please try my [fix-424 branch](https://github.com/genodeftest/exaile/tree/fix-424) and confirm it fixes this bug?

**Comment by jondoe1337** [comment]
@genodeftest Works like charm!

Also the initial startup time went down to 2 or 3 seconds. :)

**Comment by genodeftest** [comment]
Thanks for your feedback!
