### ISSUE TITLE
Track duration not showed for wave files

### ISSUE THREAD

**Issue by XzuRukneg** [exaile/exaile#440]
Cf screenshot: all the 0:00 times are waves files. When I play it, the time appear, but disappear if I close and open exaile, even if I save the playlist.

### Environment

Xubuntu 16.04

GStreamer: 1.8.3
GTK+: 3.18.9
Locale: fr_FR UTF-8
Mutagen: 1.31
PyGObject: 3.20.0
Python: 2.7.12
* Exaile Version: 4.0.0beta2

**Comment by genodeftest** [comment]
I can't see any screenshot.
I cannot reproduce your issue with the sample files from [exaile/exaile-test-files](https://github.com/exaile/exaile-test-files). In case your file is free of copyright restrictions (e.g. because you created it yourself), feel free to upload it there. Without an example, it is hard to debug this behavior.

**Comment by XzuRukneg** [comment]
![ex-time](https://user-images.githubusercontent.com/4454843/32241325-1e8d78b4-be70-11e7-93af-b8d5ec71f002.png)

all the 0:00 are .wav files

**Comment by XzuRukneg** [comment]
![ex-time2](https://user-images.githubusercontent.com/4454843/32241455-71f7be4c-be70-11e7-830a-622f32b7d997.png)

**Comment by genodeftest** [comment]
Ok, I can reproduce now. Thanks!

**Comment by genodeftest** [comment]
Please check the latest git master. Please report back in case you are seeing this issue again.
