### ISSUE TITLE
Unsolicited sharing of played songs to Last.fm and Lyricsfly (and others)

### ISSUE THREAD

**Issue by gandaro** [exaile/exaile#45]
Hello,

in the default configuration Exaile sends your played songs to Last.fm and Lyricsfly unencryptedly, without telling the user this before he starts using the program. This is a big privacy issue, because the user’s music library is being shared with untrustworthy parties on the Internet like that.  These plug-ins should be opt-ins.  VLC solved this issue by asking the user if he wants VLC to search for cover art on the Internet on the first start.

Regards,
Jakob Kramer

**Comment by virtuald** [comment]
Sorry for the delayed response. I don't have enough time to work on Exaile until probably April. However, you raise a valid concern, and some type of setup dialog seems like a good approach to me. Feel free to submit a pull request.

**Comment by sjohannes** [comment]
The Lyricsfly plugin has been removed since 3.4.0 so that's not an issue anymore. Looking at the [current defaults](https://github.com/exaile/exaile/blob/master/data/config/settings.ini), the only thing that phones home without user interaction is lastfmcovers (when playing a track without local cover). lastfmdynamic is a close second; it requires the user to enable dynamic playlist, but doesn't make it obvious that it's sending song info to last.fm.

Should we remove both from the default list for now? If we do this, remote cover fetching will silently fail and the Dynamic Playlist button will show a "Requires plugins providing dynamic playlists" tooltip.

**Comment by virtuald** [comment]
I would not be opposed to removing either of those plugins from the default. Let's do that.
