### ISSUE TITLE
multimedia keybinder not working

### ISSUE THREAD

**Issue by tecan** [exaile/exaile#468]
using most recent version of git exaile xkeybinder does not function against the python-keybinder included with ubuntu v0.3.1  i tried the updated keybinder lib from the plugin file url aswell. was wondering if mmkeys would make a better alternative than the gnomemm.

**Comment by genodeftest** [comment]
Are you running Exaile under a wayland session? If yes, global key bindings cannot work.

There is no "xkeybinder" in Exaile. You probably mixed something up.

There is MPRIS support in GNOME and Xfce now, and probably also in all other important desktop environments. You might try to use the "mpris" plugin instead for multimedia keybindings.

Are there any logging entries?

**Comment by sjohannes** [comment]
As of latest development version, there are two plugins that can potentially handle multimedia keys:

* MPRIS 2 (under Utility): Should work on GNOME, MATE, and probably others; the hotkeys are configurable through the desktop's keyboard settings.

* Keybinder (under Hotkeys): This should work on the more lightweight setups, for example if you use plain Fluxbox or IceWM.

**Comment by tecan** [comment]
thanks i've been looking for that :) mpris should be under the hotkey section rather than utilitys or atleast have some kind of comment mentioning mm keys.

**Comment by sjohannes** [comment]
Yeah, that needs some tweaking. The history is this: MPRIS technically isn't about hotkeys, it's for controlling media players in general (e.g. with [panel applets](https://a.fsdn.com/con/app/proj/mprisapplet/screenshots/gnome-mpris-applet-ltr.png)), that's why it's under Utility rather than Hotkeys. But GNOME since 3.20 can [act as an MPRIS client](https://help.gnome.org/misc/release-notes/3.20/#media-controls) and this is also integrated with their hotkey system.

So we'll need to somehow convey this, but I'm just not sure of the best way.
