### ISSUE TITLE
"Change language" option in the menu

### ISSUE THREAD

**Issue by asereze** [exaile/exaile#51]
I'm translating Exaile in Sardinian (at 70.1% now), a minority language spoken by more than 1.2 million people, but using the program I've not found a "change language" option, and it opens automatically in English+Italian on my PC. Could that be fixed?
Thanks for your time and work.

**Comment by virtuald** [comment]
I believe that the program uses the current locale set by the OS to open the program.

**Comment by l2212** [comment]
Yes, I think that too (I could not verify because I still have not finished the translation so it could not be in the program). The problem is that, for example, Windows 7 doesn't seem to have Sardinian in the possibilities for setting (while Windows 8 does, at least, I don't know about Osx or Linux-based OS).

**Comment by virtuald** [comment]
Hm. Well, I suppose one possible solution is we could write the preferred locale to settings, and at startup when we do locale detection we could see if the user has a preferred locale, and use that if set.

Definitely would not be able to dynamically change the locale, however. Would require a restart.

**Comment by l2212** [comment]
Yeah, that could work fine. After all, I don't think the need of a restart to apply the change would be a great problem for users, the only necessary thing would maybe be a disclaimer about that.

**Comment by genodeftest** [comment]
I don't know wheter this option exists under Windows, but under Linux/Unix you could run
`LC_ALL=sc exaile` to run exaile with sardinian locale. The `LC_ALL=sc` statement sets the environment variable for libc's locale to the language code for sardinian.

I expected this python code in exaile.py to do the trick (it should afaik), but it didn't:
```
import locale

locale.setlocale(locale.LC_ALL, 'ru_RU')
```
Maybe you can set LANG or LC_ALL in exaile.bat.

**Comment by sjohannes** [comment]
According to [1], setting locales in Windows is rather broken, and you 
have to actually set the LC_ALL environment variable.

[1] 
https://stackoverflow.com/questions/3678174/python-gettext-doesnt-load-translations-on-windows

I tried adding

   set LC_ALL=ru_RU

to exaile.bat, and it partially works. However, there is still a 
significant number of strings that don't get translated. (And it's not 
because of incomplete translation; Exaile's Russian translation almost 
100% complete.) I can't figure out what makes these strings different.
