### ISSUE TITLE
Windows: Collection panel tooltip flickers

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#554]
Steps to reproduce:

1. Have some tracks in the collection.
2. Hover on any row in the Collection panel treeview.

The tooltip will flicker like mad.

This is with the 4.0.0rc3 installer (GTK+ 3.24.0). Haven't tested if it's a general GtkTreeView issue or something specific to how we use it. I don't use the Collection panel often so I can't say for sure when this broke, but I don't think this has always been the case.

**Comment by genodeftest** [comment]
Fedora does not seem to patch the official Gtk+ builds at all, so there is no patch in Fedora which has not landed upstream already. Maybe you are using different Gtk+ versions (3.24.1 vs. 3.24), but I have not found any related commit upstream. Or maybe this issue is depending on the environment, e.g. not happening on Wayland (as wayland is the best tested platform).

**Comment by rokm** [comment]
Hmm, indeed. The tooltips are properly positioned on Fedora 29 both under X and wayland, and both with 3.24.1-1 (default) and 3.24.0-1 (manual downgrade from koji).

On the other hand, under Windows, they are properly positioned with 3.22.30-1 (default for msys2 installation) and incorrectly with both 3.24.0-1 and 3.24.1-1 (manual download from mingw repo).

**Comment by genodeftest** [comment]
Suggested workaround: Ship Exaile with Gtk3 3.22.x and wait for 3.24.x to mature. This will also prevent #558 from happening.

**Comment by sjohannes** [comment]
Works for me now on Windows with GTK+ 3.24.2 (current on MSYS). Please reopen if you still see this.
