### ISSUE TITLE
Need to split out the msys pieces from building a release

### ISSUE THREAD

**Issue by virtuald** [exaile/exaile#584]
As discussed on IRC.... this really needs to be done. One of the things holding back release(s) is that it's difficult to build a full release unless you're on Windows, because of the msys dependency which is constantly changing.

Ideally, the msys stuff could be packaged separately into something that could be reused and repackaged from Linux. Then, all we would need to do is push a tag, and travis would magically bundle everything together and push a release to github.

One thought is to use pyinstaller in a more controlled way. We could bundle the source code of exaile with the installer, using the same base pyinstaller exe each time. This base could be primed with all of the builtin imports we need (somehow?), and the external stuff too. If the stub just executed the main exaile source, we wouldn't need to rebuild the pyinstaller exe each time.

More ideas welcome. And.. I need to put together a VM with msys so we can get 4.0 out the door.

**Comment by X0rg** [comment]
Any update about it?

**Comment by virtuald** [comment]
I still think this is a good idea to pursue.

**Comment by X0rg** [comment]
I don't know if it helps, but the [Windows Build Environment](https://docs.travis-ci.com/user/reference/windows/) is available on Travis CI.

Chocolatey is installed and can be used to install Windows packages, like [MSYS2](https://chocolatey.org/packages/msys2).

**Comment by sjohannes** [comment]
The issue with Travis is that it doesn't seem to provide storage for build outputs. AppVeyor does, though it only retains files for 6 months.

Another option I hadn't considered before is [Azure Pipelines](https://www.azuredevopslabs.com/labs/azuredevops/github-integration/). I think it also provides storage, although the documentation is not clear on the limitations.

The MSYS installer is [annoying to install headlessly](https://bugreports.qt.io/browse/QTIFW-166) (it's possible but requires a custom [automation script](https://github.com/Gnucash/gnucash-on-windows/blob/bf11501af926098ff0c82fbe30baccad56ee6784/setup-mingw64.ps1#L128)). Chocolatey can save us from having to deal with this, so thanks for the mentioning it. Just a bit of a shame that the Chocolatey msys2 package is rather old and will probably cause the build to take more time (due to the initial `pacman -Syu` needing to upgrade everything).

**Comment by sjohannes** [comment]
After more digging, it turns out that MSYS2 provides a .tar.xz archive from [their SourceForge site](https://sourceforge.net/projects/msys2/files/Base/x86_64/) so there's no need to deal with the installer, even if we don't use Chocolatey.

> the Chocolatey msys2 package is rather old

This was also wrong; it's the same version as the main website.

**Comment by sjohannes** [comment]
Something I worked on in the past few days: https://github.com/sjohannes/exaile-binenv-win-appveyor

What it currently does:

1. Fetch the `python-gtk3-gst-sdk` and `exaile` repositories.
2. Run `build_win32_sdk.sh`.
3. Zip up the resulting `_build_root` and upload it as a GitHub release.

Notes:

* AppVeyor project: https://ci.appveyor.com/project/sjohannes/exaile-binenv-win-appveyor/history
  * I chose AppVeyor because the [build cache](https://www.appveyor.com/docs/build-cache/) seems useful; it will let us avoid redownloading stuff between builds.
  * AppVeyor already has MSYS2 installed so we can just use it. Unfortunately they installed lots of things we don't need, so we have to try to avoid doing a full `pacman -Syu` there.
* GitHub releases: https://github.com/sjohannes/exaile-binenv-win-appveyor/releases
  * GitHub releases has a [very generous](https://help.github.com/en/articles/distributing-large-binaries) quota, so it's good for long-term storage.
* This doesn't track changes in the `python-gtk3-gst-sdk` and `exaile` repositories. That's good, because we don't want to create a new SDK all the time; we can schedule it to run once a month or so. The downside is that we need to remember to trigger an SDK build when we add a new dependency, for example.

How to go from here to fully automated installer builds:

1. Store the URL of a known "good" SDK build in the Exaile source tree.
2. Create a very similar CI project in AppVeyor, but this time tracking Exaile itself.
3. In that CI build, rather than calling `build_win32_sdk.sh`, we download the existing SDK and extract it to the `_build_root` directory.
   * AppVeyor's build cache will let us avoid having to redownload the file every time.
4. Continue as usual with `build_win32_installer.sh`.

If anyone wants to work on this, feel free. I don't know when I'll have time to continue.

**Comment by X0rg** [comment]
I'm working on this:
* [appveyor.yml](https://github.com/X0rg/exaile/blob/master/appveyor.yml)
* [CI](https://ci.appveyor.com/project/X0rg/exaile)

But I'm stuck with the following error:
```
*** fatal error - cygheap base mismatch detected - 0x18031F410/0x180320410.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
```
After some research, people suggest to:
* Remove `C:\cygwin` to avoid conflict with `C:\cygwin64`: it doesn't solve the issue
* Reset `PATH`: it doesn't solve the issue

Any ideas?

**Comment by sjohannes** [comment]
Hm, I don't really know what's going on either. Try using the bash that is inside `_build_root`:

    set BASH=%CD%\exaile\tools\installer\_build_root\usr\bin\bash.exe --login

**Comment by X0rg** [comment]
It did not solve the problem either. But I figured out the issue: to be short, system was broken due to partial update (`pacman` does not share its database across projects).
A `pacman --noconfirm --noprogressbar -Syuu` solves this issue.

So, this is what I done:
- the SDK URL is stored in [`appveyor.yml`](https://raw.githubusercontent.com/X0rg/exaile/master/appveyor.yml) (see `SDK_NAME`, `SDK_VER` and `SDK_URL`)
- the SDK tarball is versioned and cached
- it builds the installer on every push on master (it can be disabled with `skip_non_tags: true`)
- it deploys artifact on every tag on master

Installer example: https://github.com/X0rg/exaile/releases/tag/4.0.0-test5
It can be installed on Windows 10, but Exaile fails to start with `Failed to execute script pyi_rth_pkgres`. [PyInstaller](https://github.com/exaile/pyinstaller) seems broken.

**Comment by virtuald** [comment]
Are you using our version of pyinstaller or the version from pypi? pyinstaller tends to break so whenever I install it I install our version from the sdk branch.

**Comment by sjohannes** [comment]
I tried upgrading PyInstaller but ran into [a setuptools bug](https://github.com/pypa/setuptools/issues/1118):

> distutils.errors.DistutilsPlatformError: VC 6.0 is not supported by this module

MSYS2 [patches this](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-setuptools/0004-dont-execute-msvc.patch)) so I tried installing it, but couldn't get the build process to use that instead of downloading upstream setuptools.

**Comment by X0rg** [comment]
I have added a workaround for Distutils:
`bash -lc "sed -i 's|VERSION = get_build_version()|VERSION = 14.0|' $BUILD_ROOT/mingw32/lib/python2.7/distutils/msvc9compiler.py"`
`VERSION` should be 14.0 with VS 2015, not 6.0.

With your version @sjohannes, I've got this error:
```
Collecting PyInstaller from https://github.com/sjohannes/pyinstaller/archive/sdk.zip#egg=PyInstaller
  Downloading https://github.com/sjohannes/pyinstaller/archive/sdk.zip
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  Complete output from command C:/msys64/home/appveyor/exaile/tools/installer/_build_root/mingw32/bin/python2.exe C:/msys64/home/appveyor/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/pep517/_in_process.py get_requires_for_build_wheel c:/users/appveyor/appdata/local/temp/1/tmpsjjy1j:
  Traceback (most recent call last):
    File "C:/msys64/home/appveyor/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/pep517/_in_process.py", line 207, in <module>
      main()
    File "C:/msys64/home/appveyor/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:/msys64/home/appveyor/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "c:/users/appveyor/appdata/local/temp/1/pip-build-env-xruraa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "c:/users/appveyor/appdata/local/temp/1/pip-build-env-xruraa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
      self.run_setup()
    File "c:/users/appveyor/appdata/local/temp/1/pip-build-env-xruraa/overlay/lib/python2.7/site-packages/setuptools/build_meta.py", line 126, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ImportError: No module named PyInstaller
```

**Comment by X0rg** [comment]
I found a fix for `ImportError` in pyinstaller/pyinstaller#4007. WIP...

**Comment by X0rg** [comment]
```
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by '_inst/usr/share/exaile/data'.
```
Well, [PyInstaller 3.4 adds incompatible changes](https://pyinstaller.readthedocs.io/en/v3.4/CHANGES.html):
> (minor) The destination path for –add-data and –add-binary must no longer be empty, use . instead.

So I did theses changes: X0rg/exaile@b467bab97da2fa2af383c407470f4a1cb0b597a4

___

Now, `makensis` fails ([build log](https://ci.appveyor.com/project/X0rg/exaile/builds/22948322)):
```
++ package_installer /home/appveyor/exaile/tools/installer/exaile_installer.nsi
++ build_makensis /home/appveyor/exaile/tools/installer/exaile_installer.nsi
++ /home/appveyor/exaile/tools/installer/_build_root/mingw32/bin/makensis.exe /home/appveyor/exaile/tools/installer/exaile_installer.nsi
Processing config: C:\msys64\home\appveyor\exaile\tools\installer\_build_root\mingw32\etc\nsisconf.nsh
Processing script file: "C:/msys64/home/appveyor/exaile/tools/installer/exaile_installer.nsi" (ACP)
This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information
```

**Comment by sjohannes** [comment]
I was able to build an installer locally after making the changes you mentioned, so it's strange that it crashes on AppVeyor.

However, the resulting binary still fails with the same PyInstaller error as before. Following PyInstaller's [debugging guide](https://pythonhosted.org/PyInstaller/when-things-go-wrong.html), this seems to be the cause:

```pytb
Traceback (most recent call last):
  File "C:/msys64/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
    import pkg_resources as res
  File "C:/msys64/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    # Reread the module from sys.modules in case it's changed itself
  File "C:/msys64/exaile/tools/installer/_build_root/mingw32/lib/python2.7/site-packages/pkg_resources/__init__.py", line 82, in <module>
    __import__('packaging.version')
ImportError: No module named version
```

**Comment by sjohannes** [comment]
@X0rg [I figured out the problem](https://github.com/exaile/exaile/commit/718939647bbb7788ae04d79b18b0c66575bec05c); it should have used the directory name instead of `'.'`. I found this by running with my host NSIS (still from MSYS2 but not the one inside `_build_root`); it correctly shows what the error is (couldn't find the `data` and `plugin` dirs), I don't know why the NSIS in `_build_root` just crashes.

Regarding the `msvc9compiler.py` change, I've updated the SDK builder to replace the whole file with just a `raise ImportError`, which seems to work as well.

And then I've added the `packaging` module to PyInstaller's hiddenimports to work around PyInstaller not finding `packaging.version`.

And now everything seems to work! Locally anyway, haven't gotten around to trying this on AppVeyor.

**Comment by X0rg** [comment]
@sjohannes That is a good new. So I'm rebasing on your changes and I'll try on AppVeyor.

**Comment by X0rg** [comment]
Well, 718939647bbb7788ae04d79b18b0c66575bec05c and 80baa7c0424e31a5cdb728597bfe2846ca64cf48 seem to fix `Failed to execute script pyi_rth_pkgres` error. It works like a charm with [PyInstaller-3.3.1+07a859bfa](https://github.com/exaile/pyinstaller/commits/sdk) and [SDK r24](https://github.com/sjohannes/exaile-binenv-win-appveyor/releases/tag/exaile-binenv-win-24) ([build log](
https://ci.appveyor.com/project/X0rg/exaile/builds/22959506)).
![VirtualBox_Windows_10_03_2019_12_16_56](https://user-images.githubusercontent.com/2873785/54084294-34cec200-432f-11e9-883b-9ba8fdf2ed5c.png)
___

Should I try to update SDK to retry with [PyInstaller-3.4+09bda57](https://github.com/sjohannes/pyinstaller/commits/sdk), or I can prepare a PR?

**Comment by X0rg** [comment]
It also works with an updated SDK and PyInstaller-3.4+09bda57.

You can try this version: https://github.com/X0rg/exaile/releases/tag/exaile-130 ([build log](https://ci.appveyor.com/project/X0rg/exaile/builds/22960607))

**Comment by sjohannes** [comment]
This is now implemented and working in [exaile-sdk-win](https://github.com/exaile/exaile-sdk-win). If we want to trigger builds at specific time intervals we'll have to first e-mail AppVeyor asking them to enable scheduling support on the project. Or we can just trigger a manual rebuild every once in a while.
