### ISSUE TITLE
Playlist tab context menu: Bold font

### ISSUE THREAD

**Issue by genodeftest** [exaile/exaile#606]
### Steps to Reproduce (for bugs)
1. Open Exaile
2. On any playlist tab,
3. right-click
4. have a look at the context menu

### Expected Behavior
Render the menu similar to any other menu, i.e. fonts not bold.

### Current Behavior
Fonts are rendered bold, making the menu look a bit out of place compared to other menus:
![exaile-screenshot-bold-menu](https://user-images.githubusercontent.com/934401/55580634-7ffbab00-570a-11e9-893f-001ea7433d61.png)

### Possible Solution
I don't know how to track down where the menu is set to be bold. There seems to be no 

### Environment
* Operating system: Fedora 29
  * gtk3-3.24.1-2.fc29.x86_64
  * python2-2.7.15-11.fc29.x86_64
* Exaile Version: 4.0.0rc3+acb4ad6

**Comment by sjohannes** [comment]
Confirmed with GTK 3.24.5 on Windows; I think this is due to the Adwaita rework. Somehow we're causing the menu entries to get styled using the tab label style.

It might have something to do with [this line](https://github.com/exaile/exaile/blob/acb4ad6cdb67363cb6de27896e4fd0608546c96a/xlgui/widgets/notebook.py#L214):

```py
self.page.tab_menu.attach_to_widget(self, None)
```

but I don't know how we're supposed to do it. Other apps don't have this issue (tested with Caja and MATE Terminal).

**Comment by genodeftest** [comment]
Replacing that line by
```py
self.page.tab_menu.attach_to_widget(self.page, None)
```
works around the issue. Weird…

Long term solution: we should probably do `Gtk.Popover`s instead…

**Comment by genodeftest** [comment]
@sjohannes : What do you thing about #607?

**Comment by sjohannes** [comment]
I had a look at Nautilus and GNOME Terminal's code; they don't call `attach_to_widget` on their tab popups at all.

I'm fine with #607 but I'm pretty sure what we currently do is correct. If we assume that the menu should be attached to something it should be to the tab label, not the page widget.

[I've filed a GTK bug for this.](https://gitlab.gnome.org/GNOME/gtk/issues/1807)
