### ISSUE TITLE
Hiding the status bar

### ISSUE THREAD

**Issue by phalgunlolur** [exaile/exaile#616]
Hi,

I was wondering if it is possible to hide the line frame at the very bottom of the player that shows the number of songs in the collection. I have a small screen on my ultrabook. And would like to make the most out of the screen space that I have available. So if there's an option to hide it or even something like have it show up if I hover my mouse at the very bottom, it would be great.

**Comment by sjohannes** [comment]
It's not possible at the moment, but this is something I've been thinking about as well. I wonder if there's a better place we can put the track counter label to save some vertical space. We can try with a floating label (like Nautilus), but it will inevitable cover part of the last row, and I've hated that when using Nautilus.

The status bar is also used for showing progress during collection scanning, so that will need to go somewhere else as well.

**Comment by virtuald** [comment]
The progress bar and the statusbar are actually two separate pieces, so if you hide the statusbar then the progress bar will still function whenever it is being used. There's currently a setting for the format of the statusbar -- but it's not exposed in user preferences anywhere.

Could make it so that if the statusbar format is empty and there's no status, then it just isn't shown? The status doesn't seem to be used anywhere except perhaps for buffering messages.

**Comment by luzip665** [comment]
As far as I can see there are only three possible substitutions.
So I will add preferences for this three and the status bar in total. Like the preferences for the tray icon.
Additionally I will add a provider for the status bar, as for `mainwindow-info-area-widget`
