### ISSUE TITLE
Auto-detect (+reject) duplicates and mark deleted *.mp3 songs

### ISSUE THREAD

**Issue by tobwz** [exaile/exaile#705]
Assume I load a *.m3u playlist into Exaile.

Then I drag & drop one *.mp3 file from this playlist from Windows explorer into Exaile window.
Surprisingly this is accepted.

I would have expected a popup "song already in playlist" or similar.
Or a blue colorizing of the song line to indicate the duplicate.
But nothing happened.

Similarly when I delete a *.mp3 file from the playlist in Windows Explorer then Exaile doesn't show this in the playlist.
I would have expected at least a "Refresh/check for missing songs" button/menu and mark the deleted songs in playlist with red font.

But nothing is offered by Exaile.

Could you add this in next release?

Thank you
Tobias

**Comment by virtuald** [comment]
As you've noted, Exaile only loads (essentially) a copy of the m3u into its internal playlist, so it wouldn't notice such things. My view is that an m3u is just an exported version of a playlist so that you can transfer playlists between players. It's not a backing file for any particular playlist. AFAIK, most audio players treat m3u's (and other playlist interchange formats) this way.

I agree that Exaile's playlist handling could use some improvements, but it works well enough for now that I don't imagine it would be revamped without someone stepping up and doing it. Part of the reason there are inconsistencies is because someone started revising it in 2010 and stopped halfway in the middle, and we've just fixed things but haven't really given it another hard look since then.
