### ISSUE TITLE
About: Web site link fails to open (Windows)

### ISSUE THREAD

**Issue by Chealer** [exaile/exaile#712]
### Steps to Reproduce (for bugs)
1. Open the Help menu
2. Open the About item
3. Click on Web site

### Expected Behavior
Exaile's website should open.

### Current Behavior
A dialog appears with an error indicating the link could not be displayed due to an invalid argument:

> Impossible d'afficher le lien
> L'exécution du programme d'aide a échoué (Invalid argument)

The website does not open. Exaile's log does not contain anything about this.

### Possible Solution
I imagine Exaile is assuming it runs on Unix. Either it should open the link differently on Windows, or it should not display it.

### Environment
* Operating System and version: Windows 10
* Exaile Version: 4.0.2
GStreamer: 1.16.0
GTK+: 3.24.8
GTK+ theme: Adwaita
Locale: French_Canada 1252
Mutagen: 1.40.0
PyGObject: 3.32.1
Python: 2.7.16

**Comment by rokm** [comment]
Indeed, this also happens with the latest build artifacts from the CI.

But it can also be reproduced with a minimal program using a `GtkAboutDialog` and building a Windows executable using PyInstaller. Trying to open an URI will result in an error:
```
gi.repository.GLib.Error: g-exec-error-quark: Failed to execute helper program (Invalid argument) (19)
```

The issue is that when creating the distribution for Windows, PyInstaller does not to bundle the `gspawn-win64-helper-console.exe` executable, which seems to be required for calls like `g_show_uri()` and the underlying `g_app_info_launch_uris_async()` (used by the `GtkAboutDialog` to open links). So links work when the program is launched from the source directory, but do not work for the distributed .exe version.
