### ISSUE TITLE
python3.6 compat broken in 4.1.0-beta1?

### ISSUE THREAD

**Issue by pastk** [exaile/exaile#749]
Starting from 4.1.0-beta1 Exaile doesn't start on my system (Ubuntu 18.04.5, Python 3.6)
No problem in 4.1.0-alpha1.

Likely caused by #727 ?

Here is the start log (using 4.1.0):

> (exaile.py:29836): dbind-WARNING **: 14:58:58.488: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> INFO    : Loading Exaile 4.1.0...
> INFO    : Using Python 3.6.9
> INFO    : Using PyGObject 3.26.1
> INFO    : Loading settings...
> INFO    : Using Locale en_NZ UTF-8
> INFO    : Using Mutagen 1.38
> INFO    : Using GStreamer 1.14.5
> INFO    : Reconfiguring crossfading
> INFO    : Crossfade: disabled
> INFO    : Using GTK+ 3.22.30
> INFO    : Using GTK+ theme Lubuntu-default
> ERROR   : Unhandled exception
> Traceback (most recent call last):
>   File "/usr/local/lib/exaile/xl/main.py", line 561, in __init__
>     self.__init()
>   File "/usr/local/lib/exaile/xl/main.py", line 629, in __init
>     from xlgui.widgets.info import Splash
>   File "/usr/local/lib/exaile/xlgui/widgets/info.py", line 32, in <module>
>     from xl import event, formatter, main, settings, xdg
>   File "/usr/local/lib/exaile/xl/formatter.py", line 84, in <module>
>     class ParameterTemplate(metaclass=_ParameterTemplateMetaclass):
>   File "/usr/local/lib/exaile/xl/formatter.py", line 81, in __init__
>     cls.pattern = re.compile(pattern, re.IGNORECASE | re.VERBOSE)
>   File "/usr/lib/python3.6/re.py", line 233, in compile
>     return _compile(pattern, flags)
>   File "/usr/lib/python3.6/re.py", line 301, in _compile
>     p = sre_compile.compile(pattern, flags)
>   File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
>     p = sre_parse.parse(p, flags)
>   File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
>     p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
>   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
>     p = _parse_sub(source, state, sub_verbose, nested + 1)
>   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
>     p = _parse_sub(source, state, sub_verbose, nested + 1)
>   File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
>     not nested and not items))
>   File "/usr/lib/python3.6/sre_parse.py", line 734, in _parse
>     flags = _parse_flags(source, state, char)
>   File "/usr/lib/python3.6/sre_parse.py", line 803, in _parse_flags
>     raise source.error("bad inline flags: cannot turn on global flag", 1)
> sre_constants.error: bad inline flags: cannot turn on global flag at position 94 (line 4, column 20)
>

**Comment by sjohannes** [comment]
Yeah, I think it's specifically this line:

```py
idpattern = r'(?a:[_a-z][_a-z0-9]*)'
```

because the `(?a:...)` (ASCII-only) regex syntax was added in Python 3.7. But I'm pretty sure it's not needed; [the docs](https://docs.python.org/3/library/re.html#re.A) say that the `a` flag affects character classes such as `\w`, which isn't used here.

Could you test what happens if you replace that line with this?

```py
idpattern = r'[_a-z][_a-z0-9]*'
```

I don't know what exactly it affects but look around if there is any text (tags, track length, etc) that is misformatted or causes an error to be printed to the console.

@rokm, what do you think?

**Comment by rokm** [comment]
Yeah, this one's my fault - e9bce75d72a958a9d8812e8d79551ff6f8fcb2cb.

I think perhaps the safest fix is to set `idpattern` to what [it was in python 3.6](https://github.com/python/cpython/blob/4134f154ae2f621f25c5d698cc0f1748035a1b88/Lib/string.py#L85): `r'(?-i:[_a-zA-Z][_a-zA-Z0-9]*)'`

Although I think your simplified version should also do the trick, since we explicitly compile the regex with re.IGNORECASE.

**Comment by rokm** [comment]
`idpattern = r'[_a-z][_a-z0-9]*'` seems to work under both python 3.6 and python 3.9.

**Comment by pastk** [comment]
After a day of use I didn't have any issues.

**Comment by sjohannes** [comment]
Thanks for the feedback. I'll try to release 4.1.1 with this fix soon.
