### ISSUE TITLE
Make format locally

### ISSUE THREAD

**Issue by luzip665** [exaile/exaile#795]
If I run `make format` or `make check_format` locally on master, 7 files would be reformatted.
In a PR on github this doesn't happen.

Locally executed is `black --check --diff -S *.py plugins/ xl/ xlgui/ tests/`. Seems to me to be identically to the CI lint.

Also, if I commit, the linter on github does not accept the reformattings done locally.

I'm running on Ubuntu 20.04.

**Comment by sjohannes** [comment]
The CI build installs the latest version of Black on each run; perhaps your Black installation is older?

**Comment by luzip665** [comment]
This helps. Thank you!

Would it be possible to include black in the source code to prevent version problems?

**Comment by virtuald** [comment]
IIRC it has a lot of dependencies, I don't think it makes sense to do that. As an alternative, you could have 'make check_format' or whatever check for a specific version of black and fail if it's not there. Would be easy enough to update it periodically.

**Comment by genodeftest** [comment]
_Including_ black in the source code would be bad because then we would have another copy of some external software lying around which someone would need to maintain.

In theory, we could use a git submodule for this, but I think this is too much complexity.

How about executing `pip install -u black` before executing `make format`? This can easily be done locally without the need to change any scripts at all. Or how about introducing it to `make format` but _not_ to `make check-format`. `make format` is not part of the CI whereas `make check-format` is. On the other hand, this introduces activating an internet connection every time you run `make format` which may not be intended…

**Comment by virtuald** [comment]
Definitely opposed to using pip to install something when `make format` is executed, as that's a very unexpected event, and on some systems it may be the wrong pip, or require root, or a host of bad things.

**Comment by luzip665** [comment]
For me it is okay to use the pip way and upgrade black from time to time. So there is no need to include in the project.
But I wonder that it is not possible to produce the same output across multiple versions.

So IMO this can be closed.

**Comment by virtuald** [comment]
black is intentionally not very configurable, and it's still technically in "beta" so they don't guarantee that the format is completely stable yet.
