### ISSUE TITLE
Windows build fails with "ERROR: No matching distribution found for pyinstaller (unavailable)"

### ISSUE THREAD

**Issue by sjohannes** [exaile/exaile#815]
Example run: https://ci.appveyor.com/project/ExaileDevelopmentTeam/exaile/builds/44128299

I don't think we've touched PyInstaller, so maybe this is due to new Python/pip version?

**Comment by sjohannes** [comment]
From what I can tell, the only missing piece is https://github.com/pyinstaller/pyinstaller/pull/3608 , which we use in https://github.com/exaile/exaile/blob/d922ac53dac308275b9f90ea99f301a95c6b34b6/tools/installer/exaile.spec#L51-L91

**Comment by rokm** [comment]
Indeed. We can move that filtering back to our spec file until that PR gets revisited (if ever).

**Comment by rokm** [comment]
Hmm, actually we cannot :/ Because those unnecessary plugins need to be filtered out before PyInstaller performs its binary analysis and pulls in all dependencies. This is why this was turned into the assemble hook in the first place...

I've rebased our PyInstaller fork - the branch `sdk-py3` is now synced with upstream `v5.2` tag.

**Comment by rokm** [comment]
And #816 takes care of accrued minor issues.
