### ISSUE TITLE
Icecast Radio not loading streams

### ISSUE THREAD

**Issue by dbolton** [exaile/exaile#829]
### Steps to Reproduce (for bugs)

1. Open Exaile (fresh install)
2. Choose Radio 
3. Open the Icecast Radio folder

### Expected Behavior

The Icecast Radio folder should show some stations

### Current Behavior

Instead it just says "Loading streams..." (and then never loads). At the bottom it briefly displays the message "Error connecting to Icecast server."

### Environment

* Operating System and version: Windows 10 (21H2)

* Exaile Version: 4.1.3

**Comment by rokm** [comment]
Indeed. The request URL that retrieves the genres list

https://github.com/exaile/exaile/blob/cd9588f6dd91a7598587feacfe9e34ca5964caca/plugins/icecast/__init__.py#L72-L73

is invalid, likely due to changes on the directory server's side. The new URL should probably be http://dir.xiph.org/genres, but `minidom` parser cannot parse that HTML page. I suspect the Icecast plugin needs to be rewritten to load and parse https://dir.xiph.org/yp.xml instead of the front-end web page.

**Comment by dbolton** [comment]
I'm using the latest 4.1.3-beta2 on Windows 10, but still having trouble with IceCast Radio just saying "Loading streams..." (and then never loading). At the bottom it says "Retrieving stations..." (but hasn't finished after leaving it running all day.

**Comment by luzip665** [comment]
Seems that there is one radio station that cannot be stored in the stations cache.

@sjohannes @rokm 
Can you check? The station I found is called edpou, but I cannot see anything special with it.

**Comment by luzip665** [comment]
There was missing the encoding of the cache file.

Can you try the build from https://ci.appveyor.com/project/ExaileDevelopmentTeam/exaile/builds/46448613/artifacts?
It's the installer generated by #865

**Comment by dbolton** [comment]
The latest build is pulling the Icecast Radio stations list correctly. However when I try to play any Radio station it doesn't play (including radio stations that were working in 4.1.3-beta2)

**Comment by luzip665** [comment]
There is a new issue: #867. There we go ahead for playing streams on Windows.

The stations names seem to allready broken the stations xml from xiph. Have a look for `Radio RDC` in https://dir.xiph.org/yp.xml. 
So this is not up to us.
