### ISSUE TITLE
Not playing any radio stream on Win 11

### ISSUE THREAD

**Issue by luzip665** [exaile/exaile#867]
Current head of Exaile is not playing any radio streams.

The last working build I found is 1106 from https://github.com/exaile/exaile/commit/938edd7464655aded30eec29f7c554d0737ce05c.
It stops playing starting with build 1107 from https://github.com/exaile/exaile/commit/863673cedb839925dbfe303755fc02cc6b6fd282.

**Comment by luzip665** [comment]
@sjohannes 
Please can you have a look?
It works with exaile-sdk-win in version 38.

**Comment by rokm** [comment]
Hmm, it looks like that the frozen version is trying to play the radio stream using the `curl` plugin, while the unfrozen version is using `soup` plugin, and `curl` plugin keeps timing out for whatever reason. If I temporarily remove `soup` plugin, the unfrozen version also fails to play the radio streams with the same symptoms.

The frozen version does include `soup` plugin, but fails to load it, because `libsoup-2.4-1.dll` is not collected. And this happens because in GStreamer 1.22.1 (SDK 39), the `soup` plugin is not linked against the `soup` library anymore, but probably attempts to dynamically load it at runtime. The plugin in GStreamer 1.18.5 (SDK 38) was linked against the `soup` library, so PyInstaller picked it up automatically.

I'll open a PR with workaround, i.e., the manual collection of the missing DLL(s).
